#!/usr/bin/env bash
# render_view.sh — Generate tasks_view.md from tasks.json
# Usage: bash render_view.sh "User Name"
# Requires: jq

set -euo pipefail

BRAIN_PATH="$(cd "$(dirname "$0")/../.." && pwd)"
USER_NAME="${1:?Usage: render_view.sh \"User Name\"}"
TASKS_FILE="$BRAIN_PATH/USERS/$USER_NAME/Tasks/tasks.json"
PROFILE_FILE="$BRAIN_PATH/USERS/$USER_NAME/Profile.md"
OVERRIDE_FILE="$BRAIN_PATH/USERS/$USER_NAME/Tasks/daily_override.json"
VIEW_FILE="$BRAIN_PATH/USERS/$USER_NAME/Tasks/tasks_view.md"
TODAY=$(date +%Y-%m-%d)

if [[ ! -f "$TASKS_FILE" ]]; then
  echo "No tasks file found at: $TASKS_FILE" && exit 1
fi

# --- Build priority order (same logic as score_tasks.sh) ---
PRIORITY_ORDER=()
if [[ -f "$OVERRIDE_FILE" ]]; then
  override_date=$(jq -r '.date' "$OVERRIDE_FILE")
  if [[ "$override_date" == "$TODAY" ]]; then
    mapfile -t PRIORITY_ORDER < <(jq -r '.order[]' "$OVERRIDE_FILE")
  fi
fi
if [[ ${#PRIORITY_ORDER[@]} -eq 0 ]]; then
  in_section=false
  while IFS= read -r line; do
    if [[ "$line" == "## Life Priorities" ]]; then in_section=true; continue; fi
    if [[ "$in_section" == true ]]; then
      if [[ "$line" =~ ^##[[:space:]] ]]; then break; fi
      if [[ "$line" =~ ^[0-9]+\.[[:space:]](.+)$ ]]; then
        PRIORITY_ORDER+=("${BASH_REMATCH[1]}")
      fi
    fi
  done < "$PROFILE_FILE"
fi

TOTAL_CATS=${#PRIORITY_ORDER[@]}

# --- Score for top 3 ---
top3_lines=()
while IFS= read -r task_json; do
  title=$(echo "$task_json" | jq -r '.title')
  category=$(echo "$task_json" | jq -r '.category')
  priority=$(echo "$task_json" | jq -r '.priority')
  due_date=$(echo "$task_json" | jq -r '.due_date // empty')
  streak=$(echo "$task_json" | jq -r '.streak_count // 0')
  cat_weight=1
  for i in "${!PRIORITY_ORDER[@]}"; do
    if [[ "${PRIORITY_ORDER[$i]}" == "$category" ]]; then cat_weight=$(( TOTAL_CATS - i )); break; fi
  done
  case "$priority" in High) pw=3;; Medium) pw=2;; *) pw=1;; esac
  urgency=0
  if [[ -n "$due_date" ]]; then
    if [[ "$due_date" < "$TODAY" ]]; then urgency=10
    elif [[ "$due_date" == "$TODAY" ]]; then urgency=5
    fi
  fi
  score=$(( (cat_weight * pw) + urgency ))
  streak_tag=""; [[ "$streak" -gt 0 ]] && streak_tag=" 🔥${streak}"
  due_tag=""; [[ -n "$due_date" ]] && due_tag=" *(due $due_date)*"
  top3_lines+=("$score|**[$category]** $title${streak_tag} — ${priority}${due_tag}")
done < <(jq -c '.tasks[] | select(.status == "pending")' "$TASKS_FILE")

# --- Build output ---
{
  echo "# Task View — $USER_NAME"
  echo ""
  echo "*Auto-generated by LogCore. Do not edit manually — changes will be overwritten.*"
  echo "*Last generated: $(date '+%Y-%m-%d %H:%M')*"
  echo ""
  echo "---"
  echo ""
  echo "## 🎯 Top 3 Right Now"
  echo ""

  if [[ ${#top3_lines[@]} -eq 0 ]]; then
    echo "*No pending tasks.*"
  else
    rank=1
    while IFS='|' read -r _ line; do
      echo "$rank. $line"
      (( rank++ ))
    done < <(printf '%s\n' "${top3_lines[@]}" | sort -t'|' -k1 -rn | head -3)
  fi

  echo ""
  echo "---"
  echo ""
  echo "## All Tasks by Priority"
  echo ""

  for cat in "${PRIORITY_ORDER[@]}"; do
    # Get pending tasks for this category
    cat_tasks=$(jq -c --arg cat "$cat" '.tasks[] | select(.status == "pending" and .category == $cat)' "$TASKS_FILE")
    if [[ -z "$cat_tasks" ]]; then continue; fi
    echo "### $cat"
    echo ""
    for pri in High Medium Low; do
      while IFS= read -r task_json; do
        [[ -z "$task_json" ]] && continue
        title=$(echo "$task_json" | jq -r '.title')
        due=$(echo "$task_json" | jq -r '.due_date // ""')
        streak=$(echo "$task_json" | jq -r '.streak_count // 0')
        t_type=$(echo "$task_json" | jq -r '.type')
        streak_tag=""; [[ "$streak" -gt 0 ]] && streak_tag=" 🔥${streak}"
        due_tag=""; [[ -n "$due" ]] && due_tag=" *(due $due)*"
        echo "- [ ] **[$pri]** $title${streak_tag}${due_tag} \`$t_type\`"
      done < <(echo "$cat_tasks" | jq -c --arg p "$pri" 'select(.priority == $p)')
    done
    echo ""
  done

  # Completed count
  done_count=$(jq '[.tasks[] | select(.status == "done")] | length' "$TASKS_FILE")
  total_count=$(jq '.tasks | length' "$TASKS_FILE")
  echo "---"
  echo ""
  echo "*Active: $total_count tasks | Completed this cycle: $done_count*"
} > "$VIEW_FILE"

echo "✓ tasks_view.md updated for $USER_NAME"
